<div class="container-fluid h-100">
	<div class="row">
    
    <div class="col-md-6 banner p-5" style="height: 100vh;">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem mt-3">
					<i class="fas fa-search fa-2x mr-3"></i>
					Siga o que lhe interessa.
				</div>
				<div class="communicationItem mt-3">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Saiba sobre o que as pessoas estão falando.
				</div>
				<div class="communicationItem mt-3">
					<i class="far fa-comment fa-2x mr-3"></i>
					Participe da conversa.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 p-5">
		<form method="post" action="/autenticar">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
			<?php
			if($this->view->login == 'erro') {
				echo "
					<div class='row'>
						<div class='col'>
							<span class='text text-danger'>*Email ou senha inválido(s)</span>
						</div>
					</div>
					";
			}
			?>
		</form>

		<div class="row pt-5 mx-5">
			<div class="col pt-5 mx-5">
				<img src="/img/twitter_logo.png" />
				<h1 class="title">Veja o que está acontecendo no mundo agora</h1>

				<h2 class="mt-5 subtitle">Participe hoje do Twitter.</h2>
				<div class="d-grid gap-2">
					<a href="/inscreverse" class="btn btn-primary mb-2">Inscrever-se</a>
				</div>
			</div>	
		</div>

    </div>

  </div>
</div>